import { vi } from 'vitest'

export const createQuasarMock = (name, additionalProps = {}) => ({
    name,
    template: `<div class="mock-${name.toLowerCase()}" data-testid="${name.toLowerCase()}"><slot /></div>`,
    props: {
        modelValue: {},
        'onUpdate:modelValue': Function,
        options: Array,
        label: String,
        dense: Boolean,
        outlined: Boolean,
        loading: Boolean,
        color: String,
        icon: String,
        title: String,
        flat: Boolean,
        round: Boolean,
        size: String,
        textColor: String,
        optionsDense: Boolean,
        ...additionalProps
    },
    emits: ['update:modelValue', 'click'],
    setup(props, { emit }) {
        return {
            updateValue: (value) => emit('update:modelValue', value),
            handleClick: () => emit('click')
        }
    }
})

export const quasarComponents = {
    QSelect: createQuasarMock('QSelect'),
    QBtn: createQuasarMock('QBtn'),
    QIcon: createQuasarMock('QIcon'),
    QSpinner: createQuasarMock('QSpinner'),
    QChip: createQuasarMock('QChip'),
    QTooltip: createQuasarMock('QTooltip'),
    QDialog: createQuasarMock('QDialog'),
    QCard: createQuasarMock('QCard'),
    QCardSection: createQuasarMock('QCardSection'),
    QInput: createQuasarMock('QInput'),
    QTable: createQuasarMock('QTable'),
    QTh: createQuasarMock('QTh'),
    QTr: createQuasarMock('QTr'),
    QTd: createQuasarMock('QTd'),
    QCheckbox: createQuasarMock('QCheckbox'),
    QRadio: createQuasarMock('QRadio'),
    QToggle: createQuasarMock('QToggle'),
    QSlider: createQuasarMock('QSlider'),
    QRange: createQuasarMock('QRange'),
    QSeparator: createQuasarMock('QSeparator'),
    QSpace: createQuasarMock('QSpace'),
    QToolbar: createQuasarMock('QToolbar'),
    QToolbarTitle: createQuasarMock('QToolbarTitle'),
    QHeader: createQuasarMock('QHeader'),
    QDrawer: createQuasarMock('QDrawer'),
    QPageContainer: createQuasarMock('QPageContainer'),
    QPage: createQuasarMock('QPage'),
    QLayout: createQuasarMock('QLayout'),
    QItem: createQuasarMock('QItem'),
    QItemSection: createQuasarMock('QItemSection'),
    QItemLabel: createQuasarMock('QItemLabel'),
    QList: createQuasarMock('QList'),
    QExpansionItem: createQuasarMock('QExpansionItem'),
    QTabs: createQuasarMock('QTabs'),
    QTab: createQuasarMock('QTab'),
    QTabPanels: createQuasarMock('QTabPanels'),
    QTabPanel: createQuasarMock('QTabPanel'),
    QMenu: createQuasarMock('QMenu'),
    QPopupProxy: createQuasarMock('QPopupProxy'),
    QBanner: createQuasarMock('QBanner'),
    QLinearProgress: createQuasarMock('QLinearProgress'),
    QCircularProgress: createQuasarMock('QCircularProgress'),
    QBadge: createQuasarMock('QBadge'),
    QAvatar: createQuasarMock('QAvatar'),
    QImg: createQuasarMock('QImg'),
    QVideo: createQuasarMock('QVideo'),
    QCarousel: createQuasarMock('QCarousel'),
    QCarouselControl: createQuasarMock('QCarouselControl'),
    QCarouselSlide: createQuasarMock('QCarouselSlide'),
    QScrollArea: createQuasarMock('QScrollArea'),
    QVirtualScroll: createQuasarMock('QVirtualScroll'),
    QInfiniteScroll: createQuasarMock('QInfiniteScroll'),
    QForm: createQuasarMock('QForm'),
    QField: createQuasarMock('QField'),
    QFile: createQuasarMock('QFile'),
    QEditor: createQuasarMock('QEditor'),
    QMarkupTable: createQuasarMock('QMarkupTable'),
    QTimeline: createQuasarMock('QTimeline'),
    QTimelineEntry: createQuasarMock('QTimelineEntry'),
    QTree: createQuasarMock('QTree'),
    QSplitter: createQuasarMock('QSplitter'),
    QKnob: createQuasarMock('QKnob'),
    QColor: createQuasarMock('QColor'),
    QDate: createQuasarMock('QDate'),
    QTime: createQuasarMock('QTime')
}